### ISSUE TITLE
Consider renaming the repositiry

### ISSUE THREAD

**Issue by jonborchardt** [allenai/varnish#10]

**Comment by codeviking** [comment]
We'd need to rename `varnish` too, as I assume you'd want this repository to be called `varnish`.

To do this we'd need to:

1. Rename `varnish` to varnish-legacy` or something like that. Maybe @schmmd knows a type of Varnish that's old that we can use as a name.
2. Update the build triggers to point at the new repository, or remove them entirely. Do we want to take the existing Varnish site down?
3. Rename this to `varnish`.

@jonborchardt Let me know if that's what you'd like to do, and if you'd like to take down the old Varnish demo while doing so.

**Comment by schmmd** [comment]
`peeling-varnish`?

**Comment by jonborchardt** [comment]
0- yes, if you have time, please do this
1- varnish-legacy seems fine (we will delete it in a month or 2)
2- we need the old site up to test parity
2.5- yes, we should consider the old varnish locked at this point forward.

**Comment by codeviking** [comment]
Ok, `varnish` has been renamed to `varnish-legacy`, and `antd-design` is now `varnish`.

I'm going to get the new domain name, `varnish.allenai.org` setup now.

**Comment by codeviking** [comment]
The new demo site URL is also now live, https://varnish.allenai.org.
