### ISSUE TITLE
AI2Banner component's click target is too wide

### ISSUE THREAD

**Issue by mjlangan** [allenai/varnish#104]
Some of our users have complained about this. Almost the entire component is a clickable link to allenai.org, which results in people inadvertently navigating to the AI2 website when they're trying to do something else.

Repro steps:
1. Navigate to https://www.beaker.org or https://leaderboard.allenai.org, both sites show the behavior (beaker's is more pronounced, as the side margins are smaller)
2. Move your mouse along the banner from right to left, noting where the pointer changes & you enter the click target. I'd take a .gif to show _exactly_ what I mean, but RecordIt doesn't capture the pointer change.

Expected:
The AI2 text/logo is clickable, but the rest of the banner isn't

Actual:
The entire banner is clickable between the page margins.

**Comment by jonborchardt** [comment]
Assigning to Nick for thought.

JonB and Sam believe that the whole bar should remain clickable, BUT that on hover the treatment changes a bit... this is nicks call
1- constrain click area to text
2- leave it as is
3- 1 or 2 and add new treatment on hover
4- other?

**Comment by Pelagic-sky** [comment]
Typical experience is to have just the logo image clickable. 
![Screen Shot 2019-08-08 at 9 26 53 AM](https://user-images.githubusercontent.com/49924841/62720450-e9dcd780-b9be-11e9-865c-3fd06f538c28.png)

**Comment by Pelagic-sky** [comment]
If this was mobile, and I line item of content, then yes, the whole row should be clickable. But since this is a header element, we should treat the logo alone as a link back.

**Comment by splittingfield** [comment]
+1 for making only the logo clickable ;-)
