### ISSUE TITLE
The header title component should use margin instead of padding.

### ISSUE THREAD

**Issue by codeviking** [allenai/varnish#106]
This surprised me.  I generally expect header elements to use margin over padding, given it's collapsible, etc.

Let's chat about this when we get around to it, as it might be appropriate. Merely cutting this as it came to mind while using it.  Definitely low pri.

**Comment by jonborchardt** [comment]
yes, do, if not already done

**Comment by jonborchardt** [comment]
no longer using padding on the header-title
