### ISSUE TITLE
We should have a license.

### ISSUE THREAD

**Issue by codeviking** [allenai/varnish#116]
We should select a license.

It should be noted in the package.json, and explicitly specified by including the license itself at the top level of the repo.

@schmmd What license do we usually use for open source projects at AI2?

**Comment by jonborchardt** [comment]
going to use MIT to stay inline with antd

**Comment by schmmd** [comment]
I proposed sticking with MIT given that it's simpler since we're forking a MIT-licensed project, and I can't imagine it will cause us any trouble at any point.
