### ISSUE TITLE
Revisit link underline hover treatment

### ISSUE THREAD

**Issue by aaronsarnat** [allenai/varnish#122]
From @Pelagic-sky:

> I really love what Tech Crunch does with their article text links
> https://techcrunch.com/2019/10/30/deadspin-exodus/ (edited) 
> They use a thin grey underline that goes to green on hover.

**Comment by jonborchardt** [comment]
if we can make this work on an a tag by itself (css animation only) then its a go, else, nope!

**Comment by jonborchardt** [comment]
```
a {
  text-decoration: none;
  border-bottom: 1px solid transparent;
  transition: all ease-in-out 1s;
}
a:hover {
  border-color: blue;
}
```

**Comment by jonborchardt** [comment]
decided not to do
