### ISSUE TITLE
Change warning color backgrounds from 2 to 1.

### ISSUE THREAD

**Issue by Pelagic-sky** [allenai/varnish#126]
R2 = R1 
G2 = G1 
B2 = B1 
O2 = O1

**Comment by codeviking** [comment]
@Pelagic-sky What about:

```
        light: color.N2,
        dark: color.B9,
```

I'm going to assume light should go to N1, but I'll leave dark as is.

**Comment by codeviking** [comment]
Ah, N1 appears to be white, so I'll redact that. I'll leave these two as is :).
