### ISSUE TITLE
need icons for varnish demo menu items

### ISSUE THREAD

**Issue by jonborchardt** [allenai/varnish#156]

**Comment by Pelagic-sky** [comment]
Colors - color-14px
Palette - palette-14px
Typography - text-14px
Buttons - buttons-14px
Links - links-14px
Forms - tutorials-14px
Icons - icons-2-14px
Spacing - spacing-14px
Breakpoints - breakpoint-14px
Header/Footer - header-footer-14px
Tables - tables-14px
Modal - modal-2-14px
Tabs - tab-14px

**Comment by jonborchardt** [comment]
added
