### ISSUE TITLE
Update link target of 'edit this page on github' to point to our fork, not antd proper

### ISSUE THREAD

**Issue by jonborchardt** [allenai/varnish#16]
this link:
![image](https://user-images.githubusercontent.com/8194065/74264949-717d0900-4cb6-11ea-839b-6fa5e784fa7a.png)

**Comment by aimichal** [comment]
Jon said this will also fix the problem with codesandbox links in the docs:

when i follow the codesandbox link, i see `Could not fetch dependencies, please try again in a couple seconds: Could not fetch version for antd@0.9.0-alpha.643e6446f: No matching version found for antd@0.9.0-alpha.643e6446f`.

the codepen link shows `ReferenceError: exports is not defined`.

stackblitz reports `Can't find packages: react react-dom antd @allenai/varnish`.
