### ISSUE TITLE
Use AI2's canonical name in all mentions.

### ISSUE THREAD

**Issue by codeviking** [allenai/varnish#176]
We should update references to AI2 (by name) to be consistent and use the canonical form.  We should use "Allen Institute for AI" at all times, instead of "Allen Institute for Artificial Intelligence", "Ai2", etc.

I think this is only in the Footer, but we should make sure any other references are updated.

**Comment by aaronsarnat** [comment]
@codeviking is this a direct quote from Oren?

> We should update references to AI2 (by name) to be consistent and use the canonical form. We should use "Allen Institute for AI" at all times, instead of "Allen Institute for Artificial Intelligence", "Ai2", etc.

**Comment by codeviking** [comment]
No, but it was the intent.

**Comment by aaronsarnat** [comment]
Cool. I was writing an email to Jen and Carissa re: legal mentions but ended up paraphrasing the same intent since i wasn't sure

**Comment by codeviking** [comment]
Ah, I'd just emphasize that we're consolidating verbiage from a branding perspective.  I'm not sure what our legal / incorporated name is -- that's likely what should go in those docs.

**Comment by codeviking** [comment]
Once complete, let's go through the same process as https://github.com/allenai/varnish/issues/205 (just for the crucial, must have ones) to make sure the verbiage is consistent.

**Comment by codeviking** [comment]
@aaronsarnat If you haven't heard back from Jenn by tomorrow, let's just drop by her office and ask her in person. I bet she could answer (regarding just the copyright) very quickly. The privacy policy and terms of use might be a trickier aspect of this that may require more time.

**Comment by codeviking** [comment]
I believe this is now resolved.  The name in the Footer shouldn't change, as per legal it needs to be our "Legal" name not our "Doing Business Name."
