### ISSUE TITLE
Force Raleway Font to use Lining Numbers

### ISSUE THREAD

**Issue by Pelagic-sky** [allenai/varnish#192]
Issue: Raleway font uses oldstyle numbers by default. This means the numbers are "oddly sized". We can force the font to use lining numbers which are all even. 

Reason to fix: Using AI2 in our headline will render the 2 as a small character. 

How to fix:
I found an old thread about this here: http://www.typophile.com/node/106745
But here is the important part.

Webfonts served by Google Fonts are sub-setted (that means its optimized, and some glyphs are removed to make the file smaller so it loads faster).

To force Google to send you the entire full file (no subsetting) you have to specify "subsetting=all".
Here is an example on how to do that for the lobster font: http://www.impallari.com/lobster#subsetting
You can do the same for Raleway or any other font.

Once you are getting the full font, in your CSS you need to add this code to activate the lnum feature in all browsers:
font-feature-settings: "lnum"
-moz-font-feature-settings: "lnum"
-webkit-font-feature-settings: "lnum"
-ms-font-feature-settings: "lnum"
-o-font-feature-settings: "lnum"

By the way, the latest Raleway release (v3) a few days ago, also include Italics and Cyrillics. Is available here: http://www.impallari.com/projects/update/100 and will also be available in Google Fonts pretty soon."

In the above example, lnum means lining numbers.

**Comment by aaronsarnat** [comment]
![image](https://user-images.githubusercontent.com/8367927/67439665-c3850c00-f5ab-11e9-9075-b5b35b810119.png)

Here's a fix: https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-numeric

Add this rule:

```
font-variant-numeric: lining-nums;
```

**Comment by aaronsarnat** [comment]
@Pelagic-sky fix for this has been merged but not yet released. Stay tuned.
