### ISSUE TITLE
LivePreview throwing browser console error

### ISSUE THREAD

**Issue by aaronsarnat** [allenai/varnish#212]
```
React does not recognize the `maxHeight` prop on a DOM element.
```

The problem might be in here somewhere:

https://github.com/allenai/varnish/blob/master/demo/src/shared/DefaultLiveProvider.tsx

![image](https://user-images.githubusercontent.com/8367927/68613832-7db5b800-0474-11ea-9e42-9272c65a6d6b.png)

**Comment by aaronsarnat** [comment]
@jonborchardt assigning to you since it looks like you were the last person to edit this file

**Comment by aaronsarnat** [comment]
Just realized this is only happening locally (on master) but not on https://varnish.staging.apps.allenai.org/ or https://varnish.apps.allenai.org/

@codeviking @jonborchardt have you guys run into this? Console errors while running master locally but what's hosted is fine? I'm seeing errors on a number of Varnish pages, but none when I look at what's hosted on Skiff. I'm perplexed.

**Comment by codeviking** [comment]
These are `warning`s (which you can derive by the `Warning:` prefix) which means that they're only output when `NODE_ENV` is `development`.  In deployed environments we set `NODE_ENV` to `production`, so these debug style messages aren't displayed.

The Varnish project has a lot of these. We need to clean them up at some point -- but for now they're safe to ignore.

**Comment by aaronsarnat** [comment]
Sounds good, thx
