### ISSUE TITLE
Remove `Raleway` font from library

### ISSUE THREAD

**Issue by aaronsarnat** [allenai/varnish#222]
This was a request from @Pelagic-sky:
Remove `Raleway` so that all headings and body text are using `Lato`.

**Comment by Pelagic-sky** [comment]
Headline 1: Lato Heavy 46
Headline 2: Lato Heavy 36
Headline 3: Lato Heavy 30
Headline 4: Lato Heavy 24
Headline 5: Lato Bold 18
Headline 6: Lato Medium 13

**Comment by Pelagic-sky** [comment]
Same line-spacing as before.

**Comment by aaronsarnat** [comment]
@Pelagic-sky we don't currently have a `Heavy` font weight in Varnish. I can add one, but the closest thing the [Google Font](https://fonts.google.com/specimen/Lato) gives us is `Black / 900`. Is that what you want for H1-4?

Here's a chart of the font weights we have access to:

![image](https://user-images.githubusercontent.com/8367927/69663927-2864d380-103c-11ea-8c14-3938211a315b.png)

**Comment by Pelagic-sky** [comment]
Black is fine
