### ISSUE TITLE
Consider adding a spacing value equal to 3rem (48px)

### ISSUE THREAD

**Issue by aaronsarnat** [allenai/varnish#226]
I think we're missing a spacing value between `xl` and `xxl`. I suspect this might be used in multiple places on `ai2-web`.
![image](https://user-images.githubusercontent.com/8367927/69265652-767e6080-0b7e-11ea-9b65-a8792e14a0f5.png)

**Comment by aaronsarnat** [comment]
@codeviking @jonborchardt @Pelagic-sky any objections to adding this to the theme?

If not, the only question is what do we call it?

**Comment by Pelagic-sky** [comment]
We could call it XXL and then upgrade 64 to XXXL

**Comment by aaronsarnat** [comment]
Fine with me, but as discussed in person with Nick, any users who are currently leveraging `xxl` in their apps will have those sizes decrease when they update Varnish.

@codeviking @jonborchardt any objections with this? If not, I'll go ahead and make a PR.

**Comment by codeviking** [comment]
👍
