### ISSUE TITLE
Invalid list structures causing Lighthouse errors

### ISSUE THREAD

**Issue by aaronsarnat** [allenai/varnish#279]
From https://github.com/allenai/prior-demo/pull/53. This seems to be an issue primarily with `Menu` and `Columns`.

From Lighthouse:

> Lists do not contain only `<li>` elements and script supporting elements (`<script>` and `<template>`).

and

> List items (`<li>`) are not contained within `<ul>` or `<ol>` parent elements.

![image](https://user-images.githubusercontent.com/8367927/74079841-ba506b80-49f1-11ea-9320-28ff6bdd31b4.png)

![image](https://user-images.githubusercontent.com/8367927/74079843-c4726a00-49f1-11ea-8502-cd6b328fb471.png)

![image](https://user-images.githubusercontent.com/8367927/74079851-d227ef80-49f1-11ea-9ad5-34af9159523b.png)

**Comment by jonborchardt** [comment]
fixed
