### ISSUE TITLE
Hovering primary Varnish buttons with a href doesn't look right.

### ISSUE THREAD

**Issue by codeviking** [allenai/varnish#286]
If a `<Button variant="primary" />` has a `href`,  it's hover state looks like:

![image](https://user-images.githubusercontent.com/801451/76785052-f3f35f80-6771-11ea-8e0c-afd8e3cd2867.png)

I suspect this is not intended, as it's hard to see the text.

**Comment by codeviking** [comment]
I ran into this again today. @jonborchardt @schmmd would you two be ok putting this in the on-call queue. It should be a quick fix, and I've ran into it several times. I imagine end users have too.

**Comment by codeviking** [comment]
Here's the fix I did for the CORD-19 explorer:
https://github.com/allenai/santiago/blob/master/ui/src/components/LinkButton.tsx

**Comment by aimichal** [comment]
Actually, this isn't fixed like it should be. <Button variant="primary" href="/">foo<Button> still renders badly.
