### ISSUE TITLE
Remove unused code from the demo

### ISSUE THREAD

**Issue by jonborchardt** [allenai/varnish#29]
Walk the code and see if there is more antd code that we can remove...

**Comment by aimichal** [comment]
I love deleting old/dead code, but I wonder why this would need to happen here. If there's an upstream change to code we deleted, that would cause a conflict. Maybe I misunderstand which code is in question.

**Comment by jonborchardt** [comment]
its such a huge code base, i want to understand each part and remove what we are not using...
any code conflicts will be easy to resolve as we deleted the file...

examples:
code to collect comments from users... we should either use it, or remove it, as it will be confusing if its there and not used....

**Comment by jonborchardt** [comment]
to be clear, the intent is to remove unused code from the build process, surveys, and demo... not from the library itself.

**Comment by aimichal** [comment]
# 👍 

Thanks for clarifying!
