### ISSUE TITLE
Error loading fonts on app load

### ISSUE THREAD

**Issue by jonborchardt** [allenai/varnish#36]
Track and fix

`Error: ENOENT: no such file or directory, open '/Users/jonathanb/code/src/github.com/allenai/ant-design/dist_varnish/@import (css) url(https:/fonts.googleapis.com/css?family=Lato:400,700|Volkhov:400,700|Roboto Mono:400,700);.less'`

**Comment by codeviking** [comment]
@jonborchardt I'm not seeing this with the latest. Can you see if you're still running into this, and if so give me the commands that you're running?

**Comment by jonborchardt** [comment]
sorry, ill clarify

i 'fixed' this by hardcoding the fonts see: https://github.com/allenai/ant-design/blob/cbb55a128831d2c84575ad206505f1b394fcad0d/shellac/generateLESS.ts#L12

so if you uncomment the import, and delete the hardcoded font... then build shellac, you should see the error.. (when you run)
