### ISSUE TITLE
Just use less.

### ISSUE THREAD

**Issue by codeviking** [allenai/varnish#45]
Right now it's pretty hard to figure out how the styles are built. I'm still not sure if it's the case, but I'm pretty sure one has to run `npm run build` before `npm start`, to produce `dist_varnish/varnish.less`.  That file is then referenced by `components/style/themes/default.less`.

Not only is this confusing, but it means the documentation provided with the library isn't valid. One can't simply start up a local instance via `npm start`.  We should at the very least modify the docs to reflect this.

That said the whole mechanism where source-code (`default.less`) references generated source-code (`dist_varnish/varnish.less`) seems wrong. Someone can't simply open the code and follow the links in the graph to put things together. Instead someone must understand the correct incantation to generate several links in the chain.

What if we just created the file `components/style/themes/varnish.less` and changed things to use that theme instead of `default.less`? I'd also propose that we consider dropping `styled` in favor of just using less for styling (less is more!) and make shellac something we generate from the LESS files.

An advantage is we'd retain the default theme unmodified. This would allow us to revert back to that if we wanted for some reason (maybe while debugging something?) and make merges from upstream easier (which I know have been hard).

**Comment by jonborchardt** [comment]
closing this issue,, we discussed and ended with:

1- when altering their components, only use less
2- when we have a new feature request, lets try to use less first, and not styled components
2b- if we like it, we will slowly migrate away from styled components in varnish
