### ISSUE TITLE
theme values are hard to use

### ISSUE THREAD

**Issue by aimichal** [allenai/varnish#58]
The syntax for using theme values feels cruel. I'm basically copy-pasting from elsewhere and adjusting:

```js
        const Message = styled.span`
            margin-left: ${({theme}) => theme.spacing.lg};
        `;
```

That's quite unreadable, my editor doesn't help with indentation (because it's a string literal, it has no business rearranging those) and styled components are more prone to errors (`margim-left`) than the `style={{marginLeft: ...}}` equivalent.

Is there a more fluent and safe way to specify styles, especially as they relate to values from the theme?

For example, inventing a new thing called `varnishStyled`, could the above be replaced with this?

```js
        const Message = varnishStyled.span({
            marginLeft: vanishStyled.theme.spacing.lg
        });
```

**Comment by jonborchardt** [comment]
i want to make it easy.. but i dont see how what you are suggesting might work... can you add more... or stop by in person...

basically... the theme must be gotten inside the css.... so
```height: ${({theme}) => theme.bla}``` is needed

you could write
```height: ${(p) => p.theme.bla}``` if its easier

**Comment by jonborchardt** [comment]
closing unless we have an idea on how to make this better
