### ISSUE TITLE
We shouldn't hardcode rem values, but rather use the themed value.

### ISSUE THREAD

**Issue by codeviking** [allenai/varnish#7]
In several spots, right now, we're setting styles like:

```
margin: 0 0 1rem;
```

The `rem` unit is ideal for certain scenarios, as it changes as the user adjusts the default font-size.  That said, doing it this way means it's not easy to update the spacing across the entire site (as it's not a value pulled from theme).  It also doesn't mix well with the default spacing provided by Material UI components, which use pixels and pull the value from `theme.spacing.unit`.

In the template we're using this formula to convert the theme value to a rem based one:

```
margin: 0 0 ${props => props.theme.spacing.unit / props.theme.typography.fontSize}rem;
```

We should evaluate this approach as a Varnish based solution and likely bake in a utility function that makes it easy to use.

We also might consider forking from the way Material UI handles spacing, provided we have a different idea of how to do it.

**Comment by codeviking** [comment]
Of note, there's already:

```
props.theme.typography.pxToRem(valueInPixels)
```

**Comment by jonborchardt** [comment]
done
