### ISSUE TITLE
There's a weird rule under the text in the demo's top menu.

### ISSUE THREAD

**Issue by codeviking** [allenai/varnish#78]
In the menu at the top of the demo there's an add light gray rule underneath the text:

![image](https://user-images.githubusercontent.com/801451/82484479-d5218a00-9a8e-11ea-9795-146dd5203470.png)

**Comment by jonborchardt** [comment]
will be fixed with https://github.com/allenai/varnish/issues/21

**Comment by jonborchardt** [comment]
fixed
