### ISSUE TITLE
Update build system to match REVIZ (skiff+docker+dist+npm, etc) 

### ISSUE THREAD

**Issue by jonborchardt** [allenai/varnish#8]
- [x] get a general sense of the codebase
- [x] ~~add docker support~~ I don't think we need this, as we'll just use what's in place already (Github actions and Github pages).
- [x] ~~get building on skiff / google build~~ ☝️ 
- [x] preserve github workflow testing
- [x] ~~fix build steps to remove unknowns (ant specific tooling) and put dist_shellac files in right place~~ Left as is, as we ran into issues when trying to change this
- [x] add config to correctly push to npm (varnish(antd+theme), shellac, etc..)

One goal is to limit future merge conflicts... so it would be nice to not completely gut the existing flow, however, we will do the cleanest change even if it makes merging harder.

**Comment by codeviking** [comment]
@jonborchardt I think this is done-ish. I don't know what the release will look like for Shellac, yet -- is that something you'd like me to figure out?

**Comment by jonborchardt** [comment]
if you would be so kind

**Comment by codeviking** [comment]
Once https://github.com/allenai/varnish/pull/79 lands I'll release our first version and close this out.

**Comment by jonborchardt** [comment]
done
