### ISSUE TITLE
to render or not to render

### ISSUE THREAD

**Issue by aimichal** [allenai/varnish#82]
The example at https://varnish.staging.apps.allenai.org/design/colors has a `const` and a `render(...)` function, but when i try that at https://varnish.staging.apps.allenai.org/design/typography it doesn't work...

![image](https://user-images.githubusercontent.com/19393950/61498188-23e62b00-a977-11e9-8178-c3e04964cafc.png)

I was trying to make the example more DRY because it was wider than the code area and hard to read.

**Comment by jonborchardt** [comment]
fixed
