### ISSUE TITLE
Add Tabs to Varnish demo

### ISSUE THREAD

**Issue by Pelagic-sky** [allenai/varnish#98]
I took a look at the stock Ant tabs and I like their design. However, I do not like the animation of the content sliding left and right on click. I would like to kill the animation and then see how tabs are implemented to make sure their font size doesn't need to be adjusted.

**Comment by codeviking** [comment]
@Pelagic-sky Is there an icon you'd like to use for the left-hand navigation for this page?

![image](https://user-images.githubusercontent.com/801451/63954946-cbf01900-ca38-11e9-8d46-a054daf5586c.png)

**Comment by jonborchardt** [comment]
all the icons in the demo are tempo, so just pick one: https://ant.design/components/icon/
@Pelagic-sky has a ticket to make new icons for demo

**Comment by codeviking** [comment]
Ah! Cool. Will do.  Thanks!
